using System.Globalization;
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text;

const string SourceUrl = "https://pds-geosciences.wustl.edu/grail/"
    + "grail-l-lgrs-5-rdr-v1/grail_1001/shadr/gggrx_1200a_sha.tab";
const string ExpectedCoefficientSha256 =
    "6865E82D4E65D635DB2A18C5FE83F28F94C7449B735E833D02BAA47422FCCD28";

return await Generate(args);

static async Task<int> Generate(string[] args)
{
    try
    {
        if (args.Length > 1) throw new ArgumentException(
            "usage: dotnet run --file scripts/generate-lunar-gravity-model.cs -- [GRGM1200A_SHA.TAB]");
        using var client = new HttpClient();
        using var response = args.Length == 0
            ? await client.GetAsync(SourceUrl, HttpCompletionOption.ResponseHeadersRead) : null;
        response?.EnsureSuccessStatusCode();
        await using Stream input = args.Length == 1
            ? File.OpenRead(Path.GetFullPath(args[0]))
            : await response!.Content.ReadAsStreamAsync();
        var coefficients = await ReadCoefficients(input);
        string root = Directory.GetParent(ScriptDirectory())!.FullName;
        string output = Path.Combine(root, "src", "WhiskerDynamics.Core",
            "LunarGravityModel.Generated.cs");
        await WriteGenerated(output, coefficients);
        Console.WriteLine($"generated {coefficients.Count} GRGM1200A coefficients in {output}");
        return 0;
    }
    catch (Exception exception)
    {
        Console.Error.WriteLine(exception.Message);
        return 1;
    }
}
static async Task<List<(int Degree, int Order, double C, double S)>>
    ReadCoefficients(Stream input)
{
    using var reader = new StreamReader(input);
    string[] header = Split(await reader.ReadLineAsync()
        ?? throw new InvalidDataException("GRGM1200A SHA file is empty."));
    if (header.Length < 8) throw new InvalidDataException("Invalid GRGM1200A SHA header.");
    double radiusKm = Double(header[0]);
    double sourceMu = Double(header[1]);
    int sourceDegree = Int(header[3]), sourceOrder = Int(header[4]);
    int normalization = Int(header[5]);
    double referenceLongitude = Double(header[6]), referenceLatitude = Double(header[7]);
    if (radiusKm != 1738.0 || sourceMu != 4902.8001224453001
        || sourceDegree != 1200 || sourceOrder != 1200 || normalization != 1
        || referenceLongitude != 0 || referenceLatitude != 0)
        throw new InvalidDataException(
            $"Unexpected header: radius={radiusKm:R}, GM={sourceMu:R}, "
            + $"degree/order={sourceDegree}/{sourceOrder}, normalization={normalization}.");

    var result = new List<(int, int, double, double)>();
    int expectedDegree = 2, expectedOrder = 0;
    string? line;
    while ((line = await reader.ReadLineAsync()) is not null)
    {
        string[] columns = Split(line);
        if (columns.Length < 4) continue;
        int degree = Int(columns[0]);
        if (degree > 50) break;
        if (degree >= 2)
        {
            int order = Int(columns[1]);
            if (degree != expectedDegree || order != expectedOrder)
                throw new InvalidDataException(
                    $"Expected coefficient ({expectedDegree}, {expectedOrder}), found ({degree}, {order}).");
            double cosine = Double(columns[2]), sine = Double(columns[3]);
            if (!double.IsFinite(cosine) || !double.IsFinite(sine) || order == 0 && sine != 0)
                throw new InvalidDataException($"Invalid coefficient ({degree}, {order}).");
            result.Add((degree, order, cosine, sine));
            if (++expectedOrder > expectedDegree) { expectedDegree++; expectedOrder = 0; }
        }
    }
    if (result.Count != 1323 || result[^1] is not (50, 50, _, _))
        throw new InvalidDataException(
            $"Expected 1323 coefficients through 50x50, found {result.Count}.");
    string checksum = CoefficientChecksum(result);
    if (checksum != ExpectedCoefficientSha256)
        throw new InvalidDataException(
            $"GRGM1200A degree-50 coefficient checksum mismatch: {checksum}.");
    return result;
}
static async Task WriteGenerated(string path,
    List<(int Degree, int Order, double C, double S)> coefficients)
{
    var source = new StringBuilder();
    source.AppendLine("// <auto-generated />");
    source.AppendLine("// Source: NASA PDS GRAIL Release 7 GRGM1200A, GGGRX_1200A_SHA.TAB.");
    source.AppendLine($"// {SourceUrl}");
    source.AppendLine($"// Degree-50 semantic SHA-256: {ExpectedCoefficientSha256}");
    source.AppendLine("// Regenerate with: dotnet run --file scripts/generate-lunar-gravity-model.cs");
    source.AppendLine("namespace WhiskerDynamics.Core;");
    source.AppendLine();
    source.AppendLine("internal static partial class LunarGravityModel");
    source.AppendLine("{");
    source.AppendLine("    private static readonly SphericalHarmonicCoefficient[] Coefficients =");
    source.AppendLine("    [");
    foreach (var coefficient in coefficients)
        source.Append("        new(").Append(coefficient.Degree).Append(", ")
            .Append(coefficient.Order).Append(", ").Append(Format(coefficient.C))
            .Append(", ").Append(Format(coefficient.S)).AppendLine("),");
    source.AppendLine("    ];");
    source.AppendLine("}");
    string temporaryPath = path + "." + Guid.NewGuid().ToString("N") + ".tmp";
    try
    {
        await File.WriteAllTextAsync(temporaryPath, source.ToString(), new UTF8Encoding(false));
        File.Move(temporaryPath, path, overwrite: true);
    }
    finally
    {
        File.Delete(temporaryPath);
    }
}

static string CoefficientChecksum(List<(int Degree, int Order, double C, double S)> coefficients)
{
    var canonical = new StringBuilder();
    foreach (var coefficient in coefficients)
        canonical.Append(coefficient.Degree).Append(',').Append(coefficient.Order).Append(',')
            .Append(coefficient.C.ToString("R", CultureInfo.InvariantCulture)).Append(',')
            .Append(coefficient.S.ToString("R", CultureInfo.InvariantCulture)).Append('\n');
    return Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(canonical.ToString())));
}
static string ScriptDirectory([CallerFilePath] string sourceFile = "") =>
    Path.GetDirectoryName(sourceFile)!;

static string[] Split(string line) =>
    line.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);

static double Double(string value) =>
    double.Parse(value, NumberStyles.Float, CultureInfo.InvariantCulture);

static int Int(string value) =>
    int.Parse(value, NumberStyles.Integer, CultureInfo.InvariantCulture);

static string Format(double value) => value == 0
    ? "0"
    : value.ToString("e16", CultureInfo.InvariantCulture);
